### ISSUE TITLE
[BUG]The vertical indentation lines are displayed abnormally.

### ISSUE THREAD

**Issue by Johnson0907** [vslinko/obsidian-outliner#289] opened 2022-03-03 04:23 UTC
**Describe the bug**
The vertical indentation lines are displayed abnormally.
I'm using the minimal theme, but the default theme has the same problem.

**Screenshots**
<img width="794" alt="截屏2022-03-03 11 59 03" src="https://user-images.githubusercontent.com/64899466/156495431-92ada5bf-1d85-4867-913d-bbfdc7e89e56.png">

**Desktop (please complete the following information):**
 - OS: Mac 12.2.1
 - Obsidian Version: 0.13.23

**Additional context**
I hope the vertical indentation lines can be displayed in reading mode too. It will allow me to maintain the same look when exporting pdf files.

**Comment by Johnson0907** [comment] 2022-03-03 04:28
Developers can refer to this plugin.
Obsidian Indentation Guides(https://github.com/mgmeyers/obsidian-indentation-guides)

**Comment by vslinko** [comment] 2022-03-04 14:00
@Johnson0907 thank you for the feedback!

looks like a duplicate of https://github.com/vslinko/obsidian-outliner/issues/288

**Closed by vslinko** 2022-03-04 14:00 UTC
Labels: bug
