### ISSUE TITLE
[BUG] Problem with the display of the lines linking bullet points

### ISSUE THREAD

**Issue by ha-ck-run** [vslinko/obsidian-outliner#274] opened 2022-02-09 17:33 UTC
At the first try, when I just installed and enabled outliner plugin, there was no such awkward display, everything was according to the image in the plugin description. After a handful of plugin installation into my vault, which I suspect that one of them might be the source of the problem, the lines started to look in a way that instead of being close and just under them, they weren't right under the regarding bullet point as it should be. 

I don't know whether this is a bug or not, but I just wanted to inform the developers and maybe I can find a solution for this problem which annoys me. In addition, I must add that this is my first entry in this platform, so I'm working on finding my way around :P

And thank you for contributing this app and its community. I really appreciate. 

![image](https://user-images.githubusercontent.com/99014503/153254867-09b0ce7b-aec5-4c5d-8a62-083cfed11ed5.png)

Note: Also the maximum line length is limited. (The one in the display options)

OS: Windows 10
Obsidian version: v0.13.23

**Comment by vslinko** [comment] 2022-02-10 06:22
@ha-ck-run thank you for the feedback!

looks like it's duplicate of https://github.com/vslinko/obsidian-outliner/issues/273

please try disabling "readable line length" until a fix is released

**Comment by Elaws** [comment] 2022-02-14 22:21
Hello @vslinko,

Even with "readable line length" and "line wrap" disabled, vertical lines have a weird behavior :

![image](https://user-images.githubusercontent.com/52013479/153956319-fddcea4a-b6db-4581-8ac9-b42c06117834.png)

OS: Windows 10
Obsidian : v.0.13.23

**Closed** 2022-02-15 07:16 UTC
Labels: bug
