### ISSUE TITLE
[BUG] Unable to structurally move sublist up/down if doc is in the sidebar

### ISSUE THREAD

**Issue by FTWynn** [vslinko/obsidian-outliner#244] opened 2021-12-30 22:26 UTC
**Describe the bug**
I can't move sublists up/down when the doc is in the sidebar. It instead shifts whatever text is in the main window, if that can be moved.

**To Reproduce**
1. Put a document with an outline in the sidebar
2. Open a different document in the main editor with the cursor on plain text
3. Put cursor in the sidebar'd doc
4. Attempt to Ctrl+Shift+up any nodes
5. Observe no change
6. Open an outline (still different from the sidebar doc) in the main editor
7. In the main window, put the cursor on a sublist that would move if shifted up or down
8. Put cursor in the sidebar'd doc
9. Attempt to crtl+shift+up
10. Observe the main document outline nodes move instead

**Expected behavior**
The doc in the sidebar should be edited, not the main window.

**Screenshots**
Will supply if necessary

**Desktop (please complete the following information):**
 - OS: ChromeOS (crostini), but also Windows
 - Obsidian Version: 0.13.14
 - Outliner Version: 2.0.5

**Comment by WhiteNoiseDev** [comment] 2022-01-09 15:10
This is obsidian's bug <https://forum.obsidian.md/t/hotkeys-commands-should-apply-to-sidebar-notes-when-they-are-focused/2740>

**Comment by FTWynn** [comment] 2022-01-10 12:06
Booo. Left my voice there to add tot the chorus.

**Comment by vslinko** [comment] 2022-01-16 13:35
@FTWynn thank you for your feedback
@WhiteNoiseDev thank you for your answer

Closing this issue since the problem is not in the plugin.

**Closed by vslinko** 2022-01-16 13:35 UTC
Labels: bug
