### ISSUE TITLE
[BUG] Part of the hyphen is still visible

### ISSUE THREAD

**Issue by swehba** [vslinko/obsidian-outliner#119] opened 2021-05-05 22:35 UTC
**Describe the bug**
When the Outliner plugin is enabled, it replaces the standard hyphens ("-") for lists in the editor with bullets. However, it displays the bullets on top of the hyphens, and part of the hyphen is still visible. Looks a bit messy.

**To Reproduce**
1. Install and enable the plugin.
2. Create a list.
3. Notice that the "-"s are replaced by "•"s.
4. Notice — particularly in the upper-right corner of each bullet — that part of the hyphen is still visible.

**Expected behavior**
I am actually surprised that the hyphens were replaced at all. If that is necessary so that they are clickable, OK, but I think it would be better to keep to the standard editor way of handling lists and just display hyphens. If you really want to display bullets, then don't allow any of the hyphen beneath the bullet to show through.

**Screenshots**
Here's what a list looks like with the Outliner plugin disabled:

![swvault_-_Obsidian_v0_12_2](https://user-images.githubusercontent.com/1922612/117217977-2d908b00-adb7-11eb-884e-2aa91044e709.jpg)

And here's what the same list looks like when the plugin is enabled:

![swvault_-_Obsidian_v0_12_2](https://user-images.githubusercontent.com/1922612/117218107-67619180-adb7-11eb-8a33-c86516ed3dd1.jpg)

Notice that a bit of each hyphen is still visible to the upper-right of each bullet.

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: 0.12.2

**Additional context**

**Comment by vslinko** [comment] 2021-05-07 09:06
@swehba Hi!

Unfortunately, I can't reproduce the issue.

Could you say what version of plugin are you using? This issue was fixed already long time ago https://github.com/vslinko/obsidian-outliner/issues/13

**Comment by swehba** [comment] 2021-05-07 17:42
I running 1.1.7. Note that the hyphen is still visible only in edit mode, not preview.

**Comment by vslinko** [comment] 2021-07-04 12:36
Should be fixed for Minimal theme in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.9

**Closed by vslinko** 2021-07-04 12:36 UTC
Labels: bug
