### ISSUE TITLE
[FEAT] Zoom out to a parent node with a hotkey

### ISSUE THREAD

**Issue by demicuz** [vslinko/obsidian-outliner#45] opened 2021-04-01 20:08 UTC
`Cmd-Shift-.` currently seems to zoom out of the whole list. To zoom out to parent nodes you have to click on the breadcrumbs. It would be useful to have a hotkey that zooms out to a parent node.

**Comment by vslinko** [comment] 2021-04-01 20:49
@demicuz Thank you for your contribution!
But it's duplicate of #9
I'm closing your issue. Please follow #9 and stay tuned!

**Closed by vslinko** 2021-04-01 20:49 UTC
Labels: enhancement
