### ISSUE TITLE
[BUG] Vertical line displaced to all the way left of the document. Intended?

### ISSUE THREAD

**Issue by Rinthe** [vslinko/obsidian-outliner#288] opened 2022-02-23 17:58 UTC
See image

![image](https://user-images.githubusercontent.com/18214/155378785-c26d65a9-bf4e-4f45-a3dd-500122d97142.png)

**Comment by crsmoore** [comment] 2022-02-24 04:42
Yeah, this is annoying.

Definitely isn't how the demo looks in the screenshots, etc.

**Comment by luzelai** [comment] 2022-02-27 06:37
I have the same issue.It seems a SERIOUS bug.

**Comment by crsmoore** [comment] 2022-02-27 17:26
> I have the same issue.It seems a SERIOUS bug.

Yeah, it basically makes this particular feature (which is the main point of the plugin) unusable.

**Comment by rivrwind** [comment] 2022-02-27 19:25
Having this issue on all themes with all plugins disabled, and the default theme. Definitely a bug.

**Comment by 133501** [comment] 2022-03-02 10:42
The issue is present only in the latest release (for me at least). Manual downgrade helped for now.

**Comment by Guvna-McBacon** [comment] 2022-03-09 20:08
Just adding to the observations for this bug. The vertical lines are "stuck" to the far left of the note object and not locked into position far left on the note page.

For example: 

If you expand your edit pane width (in live preview or source mode) width the vertical line is on the left. 

If you reduce the width of your edit pane on the screen the vertical line stays on the left until it lines up with the bullet points.

If you keep reducing the width of the edit pane, the text wraps, but the vertical line remains aligned with the bullet points. In other words, it doesn't move further to the right of the bullets and overlaps the text.

**Comment by jakemkc** [comment] 2022-03-11 17:17
I have a similar problem too.

If I press "cmd 0" to have default zoom, the vertical lines aligned perfectly

If I press "cmd +" to zoom in, the vertical lines also aligned perfectly

If I press "cmd -" to zoom out (starting from default level), then I see similar issue as reported by Rinthe

Best
Jake

**Comment by aaronsmith1203** [comment] 2022-03-16 07:12
#273

**Comment by vslinko** [comment] 2022-03-19 09:56
Thank you all for the feedback!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.3

If the problem still persists, please create a new issue.

**Closed by vslinko** 2022-03-19 09:56 UTC
Labels: bug

**Comment by cool-RR** [comment] 2022-03-19 10:05
The original problem is fixed, but there's now a new bug with the vertical lines: https://github.com/vslinko/obsidian-outliner/issues/306
