### ISSUE TITLE
[BUG] Horizontal scrollbar does not appear when having large tables 

### ISSUE THREAD

**Issue by koan-tunes** [vslinko/obsidian-outliner#203] opened 2021-10-08 11:53 UTC
**Describe the bug**
When the outliner plugin is activated **with the 'improve the styles of your lists' option enabled,** I'm no longer able to scroll horizontally when working with tables having longer text.
The table goes 'off screen'. This only happens, when the outliner plugin is activated.

**To Reproduce**
Steps to reproduce the behaviour:
1. In the outliner plugin settings enable the 'improve the styles of your lists' option
2. Create a new table
3. Put in some very long text in one of the columns
4. The scrollbar seems to disappear and one is not able to see the text anymore

**Expected behaviour**
Horizontal scrollbar should appear, when there is a large table

**Screenshots**
<img width="818" alt="outliner-missing-scrollbar" src="https://user-images.githubusercontent.com/58424554/136552278-ab1e8b22-2cf6-47e4-a618-cd56c142548c.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v0.12.15

**Comment by vslinko** [comment] 2021-12-09 19:02
@koan-tunes Thank you for your feedback. Closing this issue as a duplicate of https://github.com/vslinko/obsidian-outliner/issues/178

**Closed by vslinko** 2021-12-09 19:02 UTC
Labels: bug
