### ISSUE TITLE
[BUG]Batch indentation error

### ISSUE THREAD

**Issue by lll637637** [vslinko/obsidian-outliner#42] opened 2021-03-31 19:06 UTC
![image](https://user-images.githubusercontent.com/69051504/113197176-ec2c2d80-9296-11eb-9dd4-c7ccd887453e.png)
I get the wrong indentation effect after selecting bullets in batch  (Position 1) .
Right way  (Position 2) .

**Comment by vslinko** [comment] 2021-03-31 19:50
@lll637637 Thank you for your contribution! Multi line commands aren’t supported right now. Please wait for 1.2.0 release

**Comment by vslinko** [comment] 2021-04-01 21:02
Closing this issue as duplicate of #3

**Closed by vslinko** 2021-04-01 21:02 UTC
Labels: bug

**Comment by dcoales** [comment] 2021-05-16 10:58
In a similar vein, if I make a bullet a heading, then the child bullets turn red with - instead of bullets.  This is normal behaviour as the children are now indented too far.  So, I then select all the children (lets say there are 5 of them) and hit shift tab to reduce the indentation.  With outliner turned off this works fine and all the children move back the same amount.  With outliner turned on however the result is that all 5 children move back and become bullets but they are no longer at the same level.  2, 3 & 4 are sub bullets of 1.  5 is at the same level as 1.  Is this easy to fix or is that in the same area and will be fixed in 1.2.0 ?
