### ISSUE TITLE
[BUG] Letters are duplicated when zoomed in

### ISSUE THREAD

**Issue by jjsteffen3d** [vslinko/obsidian-outliner#26] opened 2021-03-28 22:16 UTC
**Describe the bug**
Letters are duplicated when zoomed in.
release 1.0.11 is working fine. 1.0.12 is the first that has the problem.

**Screenshots**
![obsidian_outliner_duplicated_letters](https://user-images.githubusercontent.com/27488268/112769885-ea0e6880-9023-11eb-8ca8-20ea9e92bd8e.gif)

**Comment by vslinko** [comment] 2021-03-28 22:24
@jjsteffen3d Cannot reproduce. Could you please update plugin to 1.0.14, restart Obsidian completely, and try again?

**Comment by jjsteffen3d** [comment] 2021-03-28 22:35
I restarted obsidian, created a new vault, installed outliner plugin 1.0.14 from community plugins and got the same result. That's weird :thinking:

**Comment by jjsteffen3d** [comment] 2021-03-28 22:38
![codemirror_error](https://user-images.githubusercontent.com/27488268/112770447-0c55b580-9027-11eb-8512-af38744ee76c.png)
Just realised, this error is popping up the consolue when zoomed in and typing

**Comment by vslinko** [comment] 2021-03-28 22:44
@jjsteffen3d could you send me your file and write some info about environment: obsidian version, os version

**Comment by jjsteffen3d** [comment] 2021-03-28 22:54
Sure, you mean the file I was typing? It's this
[test.md.zip](https://github.com/vslinko/obsidian-outliner/files/6218244/test.md.zip)

My OS is Ubuntu 20.04. Obsidian 0.11.9
I just tested it on another machine with windows 10 and fresh obsidian install with default settings, new vault, same result.

**Comment by vslinko** [comment] 2021-03-29 15:02
@jjsteffen3d Thank you for your contribution! Fixed in 1.0.16

**Closed** 2021-03-29 15:01 UTC
Labels: bug
