### ISSUE TITLE
[BUG] List markers become dots in the latest insider release

### ISSUE THREAD

**Issue by gchegr** [vslinko/obsidian-outliner#302] opened 2022-03-15 01:51 UTC
**Describe the bug**
If Outliner is on, list markers look off,

**To Reproduce**
1. Update Obsidian to 0.14.0
2. Install Outliner, disable safe mode
3. Switch to edit mode
4. Notice how list markers look as circles

**Expected behavior**
It should look similar to how it used to work before

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.14.0
![Obsidian_qAtqUP5212](https://user-images.githubusercontent.com/81404846/158290071-ee7875e1-37b3-475a-a48e-1302d2a1e8b3.png)

**Comment by vslinko** [comment] 2022-03-19 09:59
@gchegr I'm sorry, but I can't understand what you mean. where is the issue?

**Comment by gchegr** [comment] 2022-03-19 11:08
@vslinko, I can’t reproduce it on another machine, normal hyphens are displayed now, and discs are visible only on hover. They still look shifted down however.
![outliner-markers](https://user-images.githubusercontent.com/81404846/159118626-08a95e82-8ec3-4068-9417-469192b9d971.gif)

**Comment by vslinko** [comment] 2023-05-10 12:40
Unable to reproduce this right now, it might have been fixed in some version.

If you still have this problem, please tell me about your current environment:
- OS
- Obsidian version
- Outliner version
- Obsidian "Editor" and "Appearance" settings
- installed plugins
- Outliner settings

**Closed by vslinko** 2023-05-10 12:40 UTC
Labels: bug

**Comment by vslinko** [comment] 2023-05-10 13:48
If you have Outliner version 4.7.1 or higher, you can press Cmd+Shift+Alt+I or Ctrl+Shift+Alt+I and copy the information here.
