### ISSUE TITLE
[BUG] Indentation not working. Lines are getting freeze

### ISSUE THREAD

**Issue by semits20** [vslinko/obsidian-outliner#94] opened 2021-04-21 11:06 UTC
**Indentation not working. Lines are getting freeze**

**Expected Behavior**
it was expected to move to another line with ease. But i am not being able to move to the next line because the next line got frozen. Pressing Enter @ the end of the line brings me to the same line 

**Desktop**
 - OS: Windows 10
 - Obsidian Version: 0.12.1

**Additional context**
focus mode by pressing "ctrl+." is not working properly. the workspace is getting freeze.

**Comment by vslinko** [comment] 2021-04-21 15:26
@semits20 Thank you for your contribution!

Unfortunately, I can't reproduce the issue. Tried on Windows 10 and MacOS with Obsidian 0.12.1.
Could you please send a screencast with the issue and send an archive with the vault in it.

**Comment by vslinko** [comment] 2021-05-07 09:13
Closing the issue.

**Closed by vslinko** 2021-05-07 09:13 UTC
Labels: bug
