### ISSUE TITLE
[BUG] Move list and sublists up or down - hotkeys not working

### ISSUE THREAD

**Issue by aaronjz** [vslinko/obsidian-outliner#327] opened 2022-06-23 19:09 UTC
**Describe the bug**
After updating to 2.3.0, the hotkeys to move a list or sublist up and down (mine, Command + Shift + up or down arrow) is not working anymore. 

**To Reproduce**
1. Navigate to list or sublist
2. Try and move the list or sublist up or down with hotkey
3. See error

**Expected behavior**
Item (list or sublist) should move up or down depending on which direction you choose.

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Obsidian Version: 14.15

Thanks for looking into these plugin issues! I really enjoy using Outliner.

**Comment by gregorydgarcia** [comment] 2022-06-23 21:32
same as https://github.com/vslinko/obsidian-outliner/issues/325

**Comment by vslinko** [comment] 2022-06-24 08:41
Thank you for the feedback. Closing as a duplicate of of https://github.com/vslinko/obsidian-outliner/issues/325

**Closed by vslinko** 2022-06-24 08:41 UTC
Labels: bug
