### ISSUE TITLE
RFE:  Headings part of outliner

### ISSUE THREAD

**Issue by anishvash** [vslinko/obsidian-outliner#126] opened 2021-05-09 19:20 UTC
Hi,

RFE request. It will be awesome if headings can be part of the outline. For example clicking "Windows/Command . " On the heading shows only outlines/headings part of the heading clicked.  

Thanks!

**Comment by vslinko** [comment] 2021-05-10 09:41
@anishvash Thank you for your idea!

It's duplicate of #97, please follow #97 to stay in touch
Closing this issue

**Closed by vslinko** 2021-05-10 09:41 UTC
