### ISSUE TITLE
[BUG] Outliner conflicts with Obsidian's new functionality to remember fold/collapse 

### ISSUE THREAD

**Issue by jamie9090** [vslinko/obsidian-outliner#258] opened 2022-01-26 00:20 UTC
**Steps to reproduce**
I use Obsidian as an outliner with checkbox bullet points, exclusively in Live Preview mode.

![image](https://user-images.githubusercontent.com/69635548/151081725-2b8b567d-6734-4e8c-9f6d-2218e31c4fbb.png)

I have all folding options enabled. I also often use the “fold all” shortcut which collapses everything. This collapses all bullets.
From this I find that Obsidian will often not “remember” that these children bullets were collapsed.
Sometimes it even shows everything expanded as well.

So if I expand the parent point (eg: via clicking the down arrow), it will expand all children as well. 
I can replicate this by rebooting Obsidian, or clicking around different files, then coming back to this file. 
This is true in the same session, when rebooting Obsidian, and across devices.

Disabling Outliner seems to bring it more stability.

**Expected result**
I would love for Obsidian to remember the indents of sub-points. Including across devices.

**Actual result**
Obsidian does not remember the collapsed state of children bullets when expanding a parent bullet point.

**Environment**
Windows 11

**Comment by vslinko** [comment] 2022-01-27 08:36
@jamie9090 thank you for your feedback, but I can't reproduce the issue. Could your please provide steps to reproduce or a screen recording?

**Comment by jamie9090** [comment] 2022-02-01 00:40
I'm struggling to reproduce systematically. It's a bit inconsistent.

Might be conflict with Minimal Theme. Will keep you posted.

**Comment by vslinko** [comment] 2022-02-01 08:08
It's possible that the Outliner plugin is resetting the folding state. I'll think how to fix that.

**Comment by vslinko** [comment] 2022-02-01 15:22
@jamie9090 should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.1.1

**Closed by vslinko** 2022-02-01 15:22 UTC
Labels: bug
