### ISSUE TITLE
[BUG] enter key not outdenting when using tab to create bullets

### ISSUE THREAD

**Issue by vincekd** [vslinko/obsidian-outliner#209] opened 2021-10-20 13:12 UTC
**Describe the bug**
If you create a bullet list with "\<TAB\>" rather than "\<SPACE\>", hitting enter on an empty line exits the list rather than outdenting.

**To Reproduce**
1. Create a new note
2. Create a bullet point list by hitting "-" + "\<TAB\>"
3. Type something, hit enter, indent with tab
4. hit enter

**Expected behavior**
The bullet should outdent, like it does when using spaces.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: v0.12.19

**Comment by vslinko** [comment] 2021-12-09 07:45
@vincekd Thank you for the feedback. Unfortunately I can't reproduce the issue. `Enter` outdents empty lines with TAB indentation. Could you please provide more information such as screen recording, broken file.

![Screen Recording 2021-12-09 at 10 34 51 mov](https://user-images.githubusercontent.com/205823/145354726-191ba25a-a7b4-4c9c-8f7b-1a488b4c3781.gif)

**Comment by vincekd** [comment] 2021-12-09 13:07
Looks like you're creating the bullet points by a shortcut that's only inserting a space after the `-`, not a tab character.
![tab-obsidian](https://user-images.githubusercontent.com/641433/145401846-1198f349-5136-4277-8ac4-0479a63c6721.gif)

**Comment by vslinko** [comment] 2021-12-09 18:38
@miluoshi now I got it, thank you. should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.4.1

**Closed by vslinko** 2021-12-09 18:38 UTC
Labels: bug
