### ISSUE TITLE
[BUG] Indents are single spaces since latest update

### ISSUE THREAD

**Issue by Dreamsync** [vslinko/obsidian-outliner#28] opened 2021-03-28 23:15 UTC
**Describe the bug**
Since latest update with new auto undent with multiple enter presses, the tab feature is now not working as expected - it is doing single spaces rather than full tabs. I can undent with shift+tab, but tab alone only indents a single space.

**Desktop (please complete the following information):**
 - OS: OSX
 - Obsidian Version: 0.11.9

**Comment by danieltomasz** [comment] 2021-03-28 23:22
I can confirm that it persist in Outline 1.0.14

**Comment by ShreyasKallingal** [comment] 2021-03-29 00:44
Do you have steps to reproduce this behavior? It's working fine for me.

**Comment by Dreamsync** [comment] 2021-03-29 00:51
I saw in Discord that someone had an unrelated issue with this plugin and restarting Obsidian fixed it.

I just now closed and reopened Obsidian and it solved the issue for me.

So, there is something funny going on, but i think we can consider this closed with the caveat that it should be made clear that restarting Obsidian is sometimes required to clear little bugs like this.

**Comment by Dreamsync** [comment] 2021-03-29 03:16
I spoke too soon - looks like the issue is happening again.

https://www.loom.com/share/661706943ab54963b8865ca4f6566fd9

**Comment by ShreyasKallingal** [comment] 2021-03-29 03:30
Ah, yeah this happened to me. Probably best to keep this open until it's addressed.

**Comment by Philipp0205** [comment] 2021-03-29 12:16
Same for me. For a temporary fix just downgrade  to the 1.0.13 (create a folder in .obsidian/plugins/ and put the main.js in there).

**Comment by vslinko** [comment] 2021-03-29 13:04
@Dreamsync Can't reproduce the issue. Could you please check your tabulation settings?

<img width="1792" alt="Screenshot 2021-03-29 at 16 04 27" src="https://user-images.githubusercontent.com/205823/112840848-7b272300-90a8-11eb-9db1-514e9baf6c87.png">

**Comment by Quorafind** [comment] 2021-03-29 14:11
@vslinko I can repro it if I closed the option to use spaces rather than tabs, which is normal before 1.0.14. But things went normal if I open the option.

**Comment by vslinko** [comment] 2021-03-29 14:57
@Quorafind Looks like it's expected behaviour since I added indentation detector.
When your choice in Obsidian settings to use tabs, plugin adds tabs, otherwise it adds spaces.

Please close the issue If you agree.

**Comment by Quorafind** [comment] 2021-03-29 15:20
@vslinko yes, but I didn't find an option to close issue.. Sorry

**Comment by danieltomasz** [comment] 2021-03-29 15:24
@Quorafind 
Don't  you see any option  on the left to comment button?
![image](https://user-images.githubusercontent.com/7980381/112859907-98adba00-90b3-11eb-9526-eac8dc18aa3c.png)

**Comment by danieltomasz** [comment] 2021-03-29 15:54
in 1.0.16 Tab indenting after writiing any text in the bullet doesn't work

**Comment by Dreamsync** [comment] 2021-03-29 16:45
The issue persists.

I just now updated the outliner plugin to the most recent update, and double checked that the tab indentation setting is turned on in the Editor settings.

With outliner plugin activated, tabs are only creating single spaces.. if i turn off outliner plugin, tabs work properly.

**Comment by danieltomasz** [comment] 2021-03-29 16:55
With tab turned off only one space to indent is possible to produce in outline mode.
This is produced when I try to outline

```
- A
 - B
  - C
   - C
   - D
   - E
    - F
```

![image](https://user-images.githubusercontent.com/7980381/112871756-e3cdca00-90bf-11eb-83d5-a1367ca1bd7b.png)

**Comment by danieltomasz** [comment] 2021-03-29 20:10
In 1.0.18 after update the behavior persisted, but turning on and off "Use Tab" in Obsidian Editor helped and Tab started working as expected, I will observe further

**Comment by iiz00** [comment] 2021-03-29 23:19
In 1.0.18, even if 'Use Tabs' is on, indent seems to consist of spaces, not tab.

**Comment by vslinko** [comment] 2021-03-31 19:16
Fixed one broken case in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.19 and also added debug logs.

Please check that problem is solved for you.

If it's not, please send video or gif with debug logs enabled:
- Enable debug mode in the plugin settings tab
- Open DevTools by pressing `Cmd+Option+I` or `Control+Shift+I`
- Reproduce an issue while screen is recorded

**Comment by vslinko** [comment] 2021-04-01 20:10
Closing the issue. If problem still exists please reopen the issue or create a new one.

**Comment by santiyounger** [comment] 2021-04-02 20:17
This plugin is amazing! however I've had the exact same issue.

 The issue comes and goes almost randomly. I was about to record a video and all of the sudden the error disappeared. but it's the exact same thing where it creates spaces instead of indents. 

I set things up in setting > editor as shown in screenshot above

It's after some times when I refresh Obsidian that the error goes away, but it comes back randomly.

If it returns I can record my screen with inspector to show

I'm on version 1.0.23
Linux Garuda
Obsidian 0.11.12

**Comment by vslinko** [comment] 2021-04-03 08:44
Found another invalid case.

If Obsidian "Use tab" setting never changed, Obsidian says to plugin it's `undefined` and in this case plugin assumes that it's 1 whitespace.

**Comment by vslinko** [comment] 2021-04-03 08:52
Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.25

Please check and report

**Closed** 2021-04-05 20:46 UTC
Labels: bug
