### ISSUE TITLE
[BUG]Use "TAB" to indent invalid

### ISSUE THREAD

**Issue by lll637637** [vslinko/obsidian-outliner#64] opened 2021-04-06 10:54 UTC
![image](https://user-images.githubusercontent.com/69051504/113700518-84983700-9709-11eb-9ca3-c5c1698a810f.png)
"B" Use "TAB" to indent invalid 

![image](https://user-images.githubusercontent.com/69051504/113701073-3df70c80-970a-11eb-83dd-a3452655b056.png)
---
---
**The second little question**
![image](https://user-images.githubusercontent.com/69051504/113701998-8105af80-970b-11eb-880d-f618e2aa62ab.png)

After using "shift+enter", "A1" should be located below "A", no need to press "TAB"

**Comment by vslinko** [comment] 2021-04-06 19:01
@lll637637 Thank you for your issue! Your screenshots are great!

This issue is duplicate of #38 so I'm closing it. Please follow #38

**Closed by vslinko** 2021-04-06 19:01 UTC
Labels: bug
