### ISSUE TITLE
[BUG] This plugin does not support your device.

### ISSUE THREAD

**Issue by gnat** [vslinko/obsidian-outliner#295] opened 2022-03-08 23:48 UTC
![Screenshot_20220308-154518202](https://user-images.githubusercontent.com/24665/157344984-ced000c0-8c37-4b6b-91d6-38d5111941b4.jpg)

**Describe the bug**
Cannot install on Android.

**Desktop (please complete the following information):**
 - OS: Android
 - Obsidian Version: 38

**Comment by vslinko** [comment] 2022-03-09 07:04
@gnat thank you for the feedback!

duplicate of https://github.com/vslinko/obsidian-outliner/pull/267

**Closed by vslinko** 2022-03-09 07:04 UTC
Labels: bug
