### ISSUE TITLE
[FEAT] Is it possible to add note for items like Dynalist does?

### ISSUE THREAD

**Issue by Bennett-Yang** [vslinko/obsidian-outliner#43] opened 2021-04-01 07:31 UTC
**Is your feature request related to a problem? Please describe.**
Obsidian-outliner does help me a lot. However, when I want to add some extra information to an item it upsets me. For example, when I wanted to append some codes to an item as an example, I found it impossible. If I create a new note for the codes in order to keep my bullet list neat, the files will be in a mess.

**Describe the solution you'd like**
Use a hotkey to create a note in a new line for the item. The note should be aligned to the item's first character and not have the bullet dot. If my description confuses you, you can try Dynalist which have this feature.

Thank you and your amazing plugin!

**Comment by ShreyasKallingal** [comment] 2021-04-01 07:50
#38 is a similar issue :)

**Comment by Bennett-Yang** [comment] 2021-04-01 08:06
@ShreyasKallingal It's definitely what I want. Thanks!

**Comment by vslinko** [comment] 2021-04-01 09:30
@Bennett-Yang thank you for your issue!
Since it is a duplicate of #38 I’m closing this issue. Please follow #38 and stay tuned.

**Closed by vslinko** 2021-04-01 09:30 UTC
Labels: enhancement
