### ISSUE TITLE
[BUG] Nodes expand when scrolling in vim mode

### ISSUE THREAD

**Issue by Philipp0205** [vslinko/obsidian-outliner#67] opened 2021-04-09 13:24 UTC
**Describe the bug**
When scrolling with J and K in vim mode nodes expand.

**To Reproduce**
1. Enable vim mode 
2. Create document with long multi line nodes and collapsed them.
3. Scroll down or up with J or K 

**Expected behavior**
Nodes should stay collapsed. 

**Screenshots**
![Peek 2021-04-09 15-23](https://user-images.githubusercontent.com/36603238/114186882-a8e15700-9947-11eb-89eb-7278e43fe215.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10

**Comment by vslinko** [comment] 2021-04-09 13:27
@Philipp0205 Thank you for your contribution!

It might be fixed in beta release https://github.com/vslinko/obsidian-outliner/releases/tag/obsidian-commands-3
Could you please install beta release and check it?

**Comment by Philipp0205** [comment] 2021-04-09 13:32
Thanks for the quick answer and your work! 

I replaced the beta main.js with my main.js and restarted obsidian. Sadly it does not resolve the issue.

**Comment by vslinko** [comment] 2021-04-09 13:47
Can't reproduce the issue :(
Could you send me your file from the screencast?

**Comment by Philipp0205** [comment] 2021-04-09 13:49
It changed a bit since the screenshot. I uploaded it here: https://u.pcloud.link/publink/show?code=XZSKzsXZbqlaxgiQigLNqju1xxot8hxyiRy0

Thanks for your help!

**Comment by vslinko** [comment] 2021-04-10 14:24
Looks like problem is in VIM mode. You could check it by disabling Outliner plugin — issue still exists.
I can make hack-ish workaround, but I don't want to support it.

It's way better to report an issue to Obsidian.

**Closed by vslinko** 2021-04-10 14:24 UTC
Labels: bug
