### ISSUE TITLE
[BUG]  Outdenting using SHIFT+TAB moves item below when other nonoutdented items exists

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#79] opened 2021-04-13 17:40 UTC
**Describe the bug**
Outdenting using SHIFT+TAB    moves item below when other nonoutdented items exist.
Not sure if bug or a feature.

**To Reproduce**
1. Make list 
```
- A
	- B
	- C
- D
```
- Go to Item B
- Outdent It using Shift + Tab
- Result 
```
- A
	- C
- B 
- D
```
**Expected behavior**
The item B will not be moved below
```
- A
- B 
	- C

- D
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] LinuxOS
 - Obsidian Version: [e.g. 22] 0.11.13
 - Outline 1.1.1

**Additional context**

**Comment by vslinko** [comment] 2021-04-13 19:38
@danieltomasz Thank you for your contribution!

This is not a bug, but a feature. And it's important one.
Outliner tries not to break the structure of the list.

For example, in your case, `C` implicitly changed the parent from `A` to `B` after unfolding `B`.

Closing for now. Feel free to open a discussion.

**Closed by vslinko** 2021-04-13 19:38 UTC
Labels: bug

**Comment by danieltomasz** [comment] 2021-04-13 19:59
Thanks for the comment!  It makes sense. Dynalist and other outlines have this behaviour but this is not a default behaviour in vanilla Obsidian.
